### ISSUE TITLE
Attu got timeout

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [zilliztech/attu#299] opened 2023-10-17 09:03 UTC
**Describe the bug:**
Attu got timeout after 60000ms when accessing milvus, how to solve it ? can i increase the timeout ?

milvus version : 2.2.10
attu version 2.2.6

![image](https://github.com/zilliztech/attu/assets/88485337/aee85868-6b3d-435c-b2be-42ecbdfa4009)

**Steps to reproduce:**
1.access attu
2.put the url of milvus

**Attu version:**

zilliz/attu:v2.2.6

**Attu version:**

**Comment by shanghaikid** [comment] 2023-10-17 09:06
how big is your collection?

**Comment by Xredys-19** [comment] 2023-10-17 09:08
about 121 millions entities

**Comment by Xredys-19** [comment] 2023-10-17 09:08
![image](https://github.com/zilliztech/attu/assets/88485337/e897944a-aaea-464e-b56b-00ebc4d621ce)

**Comment by shanghaikid** [comment] 2023-10-17 09:13
> ![image](https://user-images.githubusercontent.com/88485337/275776740-e897944a-aaea-464e-b56b-00ebc4d621ce.png)

looks like you are using different versions of attu. do the error occur in the newer version?

**Comment by Xredys-19** [comment] 2023-10-17 09:13
yes the newer version also got the timeout

**Comment by Xredys-19** [comment] 2023-10-17 09:14
the picture is before the error occurs

**Comment by Xredys-19** [comment] 2023-10-17 09:26
![image](https://github.com/zilliztech/attu/assets/88485337/203ec307-a151-4f07-a654-58bb23bc4232)

im using 256GB of ram with 5 nodes worker, i guess the cause is the resource but, is there a way to add the timeout ?

**Comment by shanghaikid** [comment] 2023-10-17 09:30
> ![image](https://user-images.githubusercontent.com/88485337/275781832-203ec307-a151-4f07-a654-58bb23bc4232.png)
> 
> im using 256GB of ram with 5 nodes worker, i guess the cause is the resource but, is there a way to add the timeout ?

yeah, I am not sure adding the timeout can fix this issue, 1 minute timeout is quite large. 

and I don't have a quick fix to add timeout in attu .

maybe upgrading the milvus to the latest version will solve the problem?

**Comment by shanghaikid** [comment] 2023-10-17 09:34
Can you can try the `ShowCollections` api when you meet this situation.

**Comment by shanghaikid** [comment] 2024-03-11 10:05
The issue has been fixed in the main branch. It will be released in this month. 

https://github.com/zilliztech/attu/pull/425

**Comment by shanghaikid** [comment] 2024-04-08 10:30
it should be fixed.

**Closed by shanghaikid** 2024-04-08 10:30 UTC
