### ISSUE TITLE
Initial indexing progress

### ISSUE THREAD

**Issue by mausch** [zilliztech/attu#91] opened 2022-09-06 09:24 UTC
**Describe the bug:**

The index creation progress bar always displays 0% when Milvus is creating the initial index (i.e. not reindexing).

Attu polls this endpoint: /api/v1/schema/index/progress?collection_name=some_collection&field_name=some_field&index_name=some_index

but Milvus 2.1.1 returns this response:

```
{statusCode: 500, message: "no index is created", error: "Bad Request"}
```

since the index hasn't been created yet.

Attu should probably report that the index doesn't exist yet, or is being created.
Ideally Milvus would report progress on initial index creation.

**Steps to reproduce:**
1. Create a Milvus collection
2. Add some data
3. Create an index on the vector field.
4. While the index is being created, visit /#/collections/some_index?activeIndex=1

**Attu version:**

2.1.0

**Comment by nameczz** [comment] 2022-09-18 03:22
@mausch 
I reproduce it in my local. It looks like Milvus bug.. Let me check it in next week.

**Comment by shanghaikid** [comment] 2022-10-18 02:14
fixed in https://github.com/zilliztech/attu/releases/tag/v2.1.2

**Closed by shanghaikid** 2022-10-18 02:14 UTC
Labels: bug
