### ISSUE TITLE
Embedding collection's Data Preview - Always show no data

### ISSUE THREAD

**Issue by DennisZhao168** [zilliztech/attu#210] opened 2023-07-03 03:36 UTC
**Describe the bug:**

**Steps to reproduce:**
1. Login into attu
2. Choose a collection
3. Go to Data Preview tab

**Attu version:**
2.2.7

**Comment by shanghaikid** [comment] 2023-07-03 11:25
what is your milvus version?

**Comment by DennisZhao168** [comment] 2023-07-03 14:22
Milvus 2.2.3

**Comment by DennisZhao168** [comment] 2023-07-03 14:51
some Milvus 2.2.8 have the same issue.

**Comment by shanghaikid** [comment] 2023-07-04 01:38
what's your schema?

**Comment by DennisZhao168** [comment] 2023-07-04 04:58
Id varchar (max 255)
emb FloatVector (dim 256)
timestamp int64

**Comment by shanghaikid** [comment] 2023-07-04 07:02
![image](https://github.com/zilliztech/attu/assets/185051/521e5fed-eaa6-4e66-ba6e-507035591f98)
![image](https://github.com/zilliztech/attu/assets/185051/12194665-8e3b-4c07-aa27-6ee94e079e2d)
I am testing with 2.2.10.  

How do you insert your data?  pymilvus? node sdk? or just import sample data from attu?

**Comment by DennisZhao168** [comment] 2023-07-04 08:15
We insert the vectors via Milvus Java SDK.

**Comment by shanghaikid** [comment] 2023-07-04 08:23
> We insert the vectors via Milvus Java SDK.

Would you like to show me the code?

**Comment by weihaopeng** [comment] 2023-07-18 12:08
<img width="928" alt="image" src="https://github.com/zilliztech/attu/assets/33681454/dff8a2ed-7d9d-4ce3-a1c1-446ddacd8cff">


Same problem. Attu 2.2.5, can show data. 2.2.7, show no data.

**Comment by daxiaraoming** [comment] 2023-07-22 02:37
duplicate of #223

**Comment by shanghaikid** [comment] 2023-11-07 05:38
> ![image](https://user-images.githubusercontent.com/116480575/280724685-89bd777a-6605-42d9-aa4c-23f7bf3d01fa.png) Embedding collection's Data Preview - Always show no data

Did you load the collection ?

**Closed** 2023-12-27 07:51 UTC
